In [1]:
import numpy as np

### Numpy (NumericPython)
Pythonda matematiksel işlemleri hızlı bir biçimde yapabilmemizi sağlayan kütüphanedir

In [2]:
p_list = list(range(1_000_000)) #klasik python listesi
np_array = np.array(p_list) #1m elemanı olan np array

In [3]:
%%timeit
[x+1 for x in p_list]

191 ms ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%%timeit
np_array + 1 

5.74 ms ± 82.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
arr1 = np.array(1)

In [6]:
type(arr1) #ndarray -> n-dimensional array 

numpy.ndarray

In [7]:
arr1.ndim # ndim -> ndimension (boyutu) - > 0 

0

In [8]:
arr2 = np.array([10,20,30])
arr2.ndim, arr2.shape #1D Array (vector)

(1, (3,))

In [9]:
arr3 = np.array([40,50,60])
arr3.ndim, arr3.shape 

(1, (3,))

In [11]:
result = arr3 + arr2
result

array([50, 70, 90])

In [12]:
result2 = arr3 - arr2 
result2 

array([30, 30, 30])

In [14]:
arr4 = np.array ([100,200])
# arr3*arr4 #Shape uyuşmazlığı olması durumunda matematiksel işlemler yapılamaz.

In [15]:
arr5 = np.array(
    [
      [10,20,30],
      [40,50,60]
    ]
)
# 2 boyutlu , 2,3 şekilli bir matris.
arr5.ndim, arr5.shape

(2, (2, 3))

In [16]:
arr6 = np.array(
    [
        [70,80,90],
        [100,110,120]
    ]
)
arr6.ndim , arr6.shape 

(2, (2, 3))

In [17]:
result = arr5 + arr6
result

array([[ 80, 100, 120],
       [140, 160, 180]])

### Dot Product (İç Çarpım)

In [18]:
np.dot(arr5,arr6)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [22]:
arr7 = np.array([
    [10,20,30],
    [40,50,60]
])
arr8 = np.array(
    [
        [10,20],
        [30,40],
        [50,60]
    ]
)
arr7.shape, arr8.shape
# Dot product -> İlk matrisin sütun sayısı, ikinci matrisin satır sayısına eşit olması.

((2, 3), (3, 2))

In [23]:
np.dot(arr7,arr8)

array([[2200, 2800],
       [4900, 6400]])

In [24]:
arr9 = np.array(
    [
        [[10,20,30,40],[30,40,50,60],[50,60,70,80]],
        [[70,80,90,100],[90,100,110,120],[110,120,130,40]]
    ]
)
# 3D array
arr9.ndim, arr9.shape

(3, (2, 3, 4))

In [25]:
arr10 = np.random.randint(0,255,(1500,1000))
arr10

array([[ 23,  88, 165, ..., 196, 103,   5],
       [ 94, 206,  44, ...,  88, 153,  64],
       [122,  45, 190, ...,  90,  27, 140],
       ...,
       [ 78, 136,   9, ..., 146, 198,  52],
       [ 68, 109, 177, ..., 246,  88, 190],
       [ 52,  51, 151, ..., 137, 106, 190]], dtype=int32)

In [28]:
!pip install Pillow

   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   ------------------------------- -------- 2.1/2.6 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 8.4 MB/s eta 0:00:00


In [29]:
from PIL import Image

In [33]:
image = Image.open("resim.jpg")

In [34]:
image_arr = np.array(image)
image_arr.ndim, image_arr.shape

(3, (618, 620, 3))

In [35]:
image_arr

array([[[254, 255, 246],
        [  0,   3,   0],
        [  0,   3,   5],
        ...,
        [  1,   1,   1],
        [  1,   1,   1],
        [  2,   2,   2]],

       [[253, 254, 246],
        [  2,   5,   0],
        [  0,   3,   2],
        ...,
        [  1,   1,   1],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 254, 249],
        [  1,   0,   0],
        [  1,   4,   0],
        ...,
        [114, 114, 114],
        [ 59,  59,  59],
        [  0,   0,   0]],

       ...,

       [[252, 255, 255],
        [  0,   2,   2],
        [  0,   0,   7],
        ...,
        [189, 221, 232],
        [109, 119, 128],
        [  0,   0,   5]],

       [[254, 255, 253],
        [  0,   1,   0],
        [  4,   5,  10],
        ...,
        [195, 224, 232],
        [109, 118, 123],
        [  6,   5,  10]],

       [[254, 255, 251],
        [  0,   2,   0],
        [  0,   0,   5],
        ...,
        [103, 130, 137],
        [ 54,  61,  67],
        [  1,   0,   2]]