In [2]:
import numpy as np

### Numpy Kütüphanesi Örnekleri

# 1. numpy.array() fonksiyonu
Bir liste veya tuple gibi veri yapılarını NumPy dizisine dönüştürür.

In [36]:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)  

[0 1 2 3 4 5]


# 2. numpy.zeros() fonksiyonu
Belirtilen boyutta sıfırlardan oluşan bir NumPy dizisi oluşturur.

In [35]:
arr1 = np.zeros((4, 3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3. numpy.arange() fonksiyonu
Belirtilen aralıkta düzenli artışlarla bir NumPy dizisi oluşturur.

In [18]:
arr2 = np.arange(0, 10, 2)
print(arr2)

[0 2 4 6 8]


# 4. numpy.linspace() fonksiyonu
Başlangıç ve bitiş noktaları arasında eşit aralıklarla belirli sayıda değer oluşturur.

In [19]:
arr3 = np.linspace(0, 5, 8)
print(arr3)

[0.         0.71428571 1.42857143 2.14285714 2.85714286 3.57142857
 4.28571429 5.        ]


# 5. numpy.random.rand() fonksiyonu
Belirtilen şekle sahip rastgele (0 ile 1 arasında) sayılardan oluşan bir dizi oluşturur

In [20]:
arr4 = np.random.rand(4, 6)
print(arr4)

[[0.28310919 0.30584742 0.46786411 0.80080715 0.67936476 0.96739052]
 [0.95239832 0.81907863 0.90792921 0.88307703 0.04755188 0.25212158]
 [0.33127315 0.50649349 0.92865121 0.15077281 0.24755271 0.11755072]
 [0.93148407 0.25380977 0.42878291 0.05022585 0.4952679  0.65242635]]


# 6. numpy.sum() fonksiyonu
Dizideki elemanların toplamını hesaplar.

In [34]:
arr5 = np.array([[5,1,3], [6,8,9]])
print(np.sum(arr5))       
print(np.sum(arr5, axis=0)) # Sütun toplamları
print(np.sum(arr5, axis=1)) # Satır toplamları

32
[11  9 12]
[ 9 23]


# 7. numpy.mean() fonksiyonu
Dizinin elemanlarının ortalamasını hesaplar.

In [23]:
arr6 = np.array([1, 2, 3, 4, 5])
print(np.mean(arr6))

3.0


# 8. numpy.sqrt() fonksiyonu
Dizinin her elemanının karekökünü hesaplar.

In [30]:
arr7 = np.array([4, 121, 16, 25])
print(np.sqrt(arr7))

[ 2. 11.  4.  5.]


# 9. numpy.exp() fonksiyonu
Dizinin her elemanının üstel fonksiyonunu (e^x) hesaplar.

In [31]:
arr8 = np.array([0, 2, 3, 4])
print(np.exp(arr8))

[ 1.          7.3890561  20.08553692 54.59815003]


# 10. numpy.unique() fonksiyonu 
Tekrar eden elemanları kaldırarak dizinin benzersiz elemanlarını döndürür.

In [32]:
arr9 = np.array([1, 2, 2, 3, 4, 4, 4, 5])
print(np.unique(arr9))

[1 2 3 4 5]
